export const ERROR_RECEIVE_CREATE_CUSTOMER = 'ERROR_RECEIVE_CREATE_CUSTOMER';
export const RECEIVE_CREATE_CUSTOMER = 'RECEIVE_CREATE_CUSTOMER';
export const REQUEST_CREATE_CUSTOMER = 'REQUEST_CREATE_CUSTOMER';