export const ERROR_RECEIVE_CUSTOMERS = 'ERROR_RECEIVE_CUSTOMERS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const REQUEST_CUSTOMERS = 'REQUEST_CUSTOMERS';

export const ERROR_RECEIVE_DELETE_CUSTOMER = 'ERROR_RECEIVE_DELETE_CUSTOMER';
export const RECEIVE_DELETE_CUSTOMER = 'RECEIVE_DELETE_CUSTOMER';
export const REQUEST_DELETE_CUSTOMER = 'REQUEST_DELETE_CUSTOMER';
